### ISSUE TITLE
vmtk_post_install.py assumes the python directory is named "Python27"

### ISSUE THREAD

**Issue by orengarb** [vmtk/vmtk#165]
The script vmtk_post_install.py, in line 17:
package_path = [f for f in sys.path if 'Python27\\lib\\site-packages' in f][0]
assumes that the python directory is named "Python27", and when it's not, an Exception is raised, and the post install script fails.

**Comment by daron1337** [comment]
This script runs only under Windows and Python27 is the only python currently supported by vmtk.
That's why we assume python dir named Python27.
We could change the line to:

  [f for f in sys.path if 'lib\\site-packages' in f][0]

but if you have a python 3 installed vmtk will link to the wrong python.
