### ISSUE TITLE
JOSS - License in LICENSE file

### ISSUE THREAD

**Issue by wouterpotters** [vmtk/vmtk#283]
According to the [JOSS reviewer guidelines](https://joss.theoj.org/about#reviewer_guidelines), the VMTK licence should be placed in a plain-text LICENSE file. Currently the license is in the copyright.txt file.

**Comment by rlizzo** [comment]
Thanks for the heads up! 

@lantiga, is there any reason the license/copyright needs to be structured this way? Or are we good to move all the text into the LICENSE file?

**Comment by rlizzo** [comment]
Thanks. Also @wouterpotters there is a separate (open source compatible) LICENCE file for the PypeS module https://github.com/vmtk/vmtk/blob/master/PypeS/LICENCE . Does this need to be included in to top level LICENSE as well?

**Comment by wouterpotters** [comment]
just a small addition to my previous remark: http://www.vmtk.org/license.html and the GitHub LICENSE seem to be dated at 2011 and/or 2012. It would be neat to update all the dates to 'until 2018' as well I guess.

**Comment by wouterpotters** [comment]
To be honest I'm no expert on the licenses, but it would be convenient for end users to see all the relevant licenses for the 1 open source software package in 1 place (the LICENSE file).

**Comment by lassoan** [comment]
A single LICENSE file in a standard location is important because applications that use many libraries often harvest license files from library repositories automatically and append them to the application's license file that is displayed to users. If you use some custom filename or location then application developers need to manually create a rule for finding license information for your library, or license information for your library may be just skipped.

Also, your library may not get listed in online software repositories or score low if license file cannot be found automatically.

**Comment by rlizzo** [comment]
Thanks for the feedback @wouterpotters and @lassoan! I've made the requested modifications to the repository and vmtk website and have linked the PRs to this issue and the main review issue. 

@wouterpotters, I'll leave this to you to close once you confirm that this is now in compliance.

**Comment by wouterpotters** [comment]
Looks good now 👍 closing this one.
