### ISSUE TITLE
Scripts not visible on Windows

### ISSUE THREAD

**Issue by fepegar** [vmtk/vmtk#309]
Hi all,

I have recently installed VMTK on Windows 10  using `conda` from `cmder`.

Are the scripts supposed to be visible from my console? I think they were when I installed VMTK on macOS.

**Comment by rlizzo** [comment]
Hi @fepegar, The scripts are not designed to be run from the Windows 10 command prompt (though you are correct that they are visible from a MacOS or Linux system).

This is partly due to no-one on the development team being a heavy Windows user, though pull requests to add such a feature are always welcome. Instead, the scripts should be used from the PypePad interface.

**Comment by fepegar** [comment]
Ok, makes sense. Thanks, @rlizzo.
