### ISSUE TITLE
module machine type 'x86' conflicts with target machine type 'x64'

### ISSUE THREAD

**Issue by zhang-qiang-github** [vmtk/vmtk#373]
I am compiling vmtk from cmake.  I select the `x64` platform as following:

![image](https://user-images.githubusercontent.com/29271051/125283985-86e2e080-e34b-11eb-9ef7-b3c2969915e0.png)

However, a bug is reported: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1112	module machine type 'X86' conflicts with target machine type 'x64' [D:\Program Files\vmtk\bin\VMTK-Build\CMakeFiles\CMakeTmp\cmTC_8ce6f.vcxproj]	VMTK	D:\Program Files\vmtk\bin\cmTC_8ce6f.dir\Debug\testCCompiler.obj	1	

```

How can I solve this bug?

**Comment by lassoan** [comment]
I don't think that recent VMTK versions can be still built with VS2015 and such ancient CMake version.

**Comment by zhang-qiang-github** [comment]
I will try to build vmtk with vs2019.

**Comment by zhang-qiang-github** [comment]
@lassoan I am building vmtk with VS2019 and Cmake 3.21.0-rc3. It is ok if I do not build python. 

If I turn `VTK_VMTK_WRAP_PYTHON` on, a bug is reported:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol PyvtkvmtkBoundaryLayerGenerator_ClassNew referenced in function PyVTKAddFile_vtkvmtkBoundaryLayerGenerator2 [D:\Program Files\vmtk\bin\VMTK-Build\vtkVmtk\Contrib\vtkvmtkContribPythonD.vcxproj]	VMTK	D:\Program Files\vmtk\bin\vtkvmtkBoundaryLayerGenerator2Python.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	1 unresolved externals [D:\Program Files\vmtk\bin\VMTK-Build\vtkVmtk\Contrib\vtkvmtkContribPythonD.vcxproj]	VMTK	D:\Program Files\vmtk\bin\VMTK-Build\vtkVmtk\bin\Release\vtkvmtkContribPythonD.dll	1	


```

**Comment by lassoan** [comment]
OK, so the problem of x86/x64 conflicts is solved. I'll close this issue now.

The unresolved external symbol in vtkContrib is due to that this component is not compatible with recent VTK versions. You can leave VTK_VMTK_CONTRIB CMake flag at the default value (OFF) to avoid this error, or fix the build errors. If you fix the build errors then please send a pull request so that others who need the features implemented in Contrib don't need to make those fixes again.
