### ISSUE TITLE
Unable to install VMTK from conda forge

### ISSUE THREAD

**Issue by robertclercpredisurge** [vmtk/vmtk#467]
Hello,

I can't install VMTK 1.5.0 from conda-forge with this command lines : 

conda install -c conda-forge vmtk==1.5.0
or
conda install conda-forge::vmtk
or
conda install vmtk

I've any time this error : 

`
PackagesNotFoundError: The following packages are not available from current channels:

  - vmtk

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

**Comment by lassoan** [comment]
VMTK does not have 1.5 version. There has not been significant feature developments since the 1.4 release, mostly just VTK compatibility fixes. A new VMTK release will be cut when VMTK is built as a standard VTK remote module, but that will probably not happen before the end of 2024.

**Comment by lassoan** [comment]
I see that while there is no 1.5 git tag, the current version is referred to as 1.5 at a number of places. I'm not sure why 1.5 is not found on conda, I don't use anaconda. @ramtingh worked the conda packages, he might have some more insight.

**Comment by ramtingh** [comment]
This was reported on conda vmtk feedstock (https://github.com/conda-forge/vmtk-feedstock/issues/24) and turned out to be due to attempting to install vmtk on apple silicon, which isn't natively supported (rosetta seems to work, although as I don't usually use macs I'm not certain). I have not gotten around to updating the build for VTK 9.3, but I haven't seen any reports of conda not working for other versions of vtk and python

**Comment by lassoan** [comment]
@ramtingh I've updated (with lots of help from Claude) VMTK to provide Python packages on PyPI and fixed the Appveyor build on all platforms. Would you have time to fire up an AI chatbot on your side and make conda packaging work again? If you would not like to spend time with this then you can also transfer ownership to me.
